config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions',  passwords: 'users/passwords'}

  # New routes for devise logging in and registering
  devise_scope :user do
    get :login, to: 'devise/sessions#new', as: 'login'
    post :login, to: 'devise/sessions#create'
    get :register, to: 'users/registrations#new', as: 'registration'
    post :register, to: 'users/registrations#create'
    get :forgotten_password, to: 'users/passwords#new', as: 'forgotten_password'
    post :forgotten_password, to: 'users/passwords#edit'
    get :change_password, to: 'users/registrations#edit', as: 'change_password'
    # post :change_password, to: 'users/registrations#update'
  end

  resources :roles
  resources :institutions
  resources :account_privacies
  resources :departments
  resources :costs
  resources :student_types
  resources :incoming_qualifications
  resources :eligibility_requirements
  resources :end_qualifications
  resources :deliver_modes
  resources :wps
  resources :stored_searches
  resources :courses do
    post :search, on: :collection
  end
  resources :members do
    post :search, on: :collection
  end
  resources :static_pages, except: [:index, :destroy], param: :name, path: 'about' do
     get :show_file, on: :member
     get :download_file, on: :member
  end

  resources :uploads, only: [:new] do
    post :upload_courses, on: :collection
  end
  resources :blogs do
    get :show_file, on: :member
    get :download_file, on: :member
  end

  resource :passwords, only: [:new, :create, :edit, :update] do
    member do
    put :reset
    end
  end


  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  # Add routes for all pages

  get :degree_search, to: 'pages#degree_search', as: 'degree_search'
  get :'degree_search/advanced', to: 'pages#advanced_search', as: 'advanced_search'

  # static pages
  post :'update-static-page', to: 'static_pages#update_static_page', as: 'update_static_page'
  get :'about', to: 'static_pages#about', as: 'about'

  post :'sending', to: 'messages#create', as: 'send_message'
  get :'members/*id/contact', to: 'members#contact', as: 'contact_member'

  get :'members/*id/validate', to: 'members#validate_member', as: 'validate_member'
  post :'members/*id/validate', to: 'members#validate_send'


  root to: 'static_pages#home'

  #stored searches
  get :'create-search', to: 'stored_searches#create_search', as:'create-search'
  get :'save-search', to: 'stored_searches#save_search', as:'save-search'
  get :'delete-search', to: 'stored_searches#delete_search', as:'delete-search'

  get :'scrape', to: 'courses#scrape', as:'scrape-courses'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/static_page.rb
# == Schema Information
#
# Table name: static_pages
#
#  id          :bigint(8)        not null, primary key
#  contents    :text             not null
#  custom_file :string
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class StaticPage < ApplicationRecord
  mount_uploader :custom_file, StaticPageCustomFileUploader

  validates :contents, presence: true
  validates :name, presence: true

  def to_param
    name
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

# Author:    Team 34: Luke Peacock
# Updated:   10.03.2019

# Static pages controller
class StaticPagesController < ApplicationController
  # Before any action in this controller, ensure user is logged in for
  # also set the current page
  before_action :authenticate_user!, only: [:update_static_page]
  before_action :set_page, only: [:show, :home, :about, :edit, :update,
                                  :show_file, :download_file]

  # render the static page contents
  def show
    @current_nav_identifier = @static_page[:name]
  end

  # renderthe home page (since this page is different)
  def home
    @current_nav_identifier = :home
    params[:name] = @current_nav_identifier
    set_page
  end

  # render about page since this page contains a different route
  def about
    @current_nav_identifier = :about
    params[:name] = @current_nav_identifier
    set_page
    render 'show'
  end


  # method to save the updated record and return a mesage
  def update
    static = @static_page
    static.assign_attributes(contents: get_contents(params),
                             custom_file: get_file(params))
    if remove_file?(params)
      static.remove_custom_file!
    end
    if static.save!
      render 'update_success'
    else
      render 'update_failure'
    end
  end

  # method to download a file to the user's computer
  # all files are named 'download.extension'
  def download_file
    send_file(@static_page.custom_file.path,
              disposition: 'attachment; filename="' + @static_page.custom_file.file.filename + '"',
              type: @static_page.custom_file.file.content_type,
              url_based_filename: true)
  end

  # method to send the file to the view to be shown to the user
  def show_file
    options = { type: @static_page.custom_file.file.content_type,
                disposition: 'inline' }
    send_file @static_page.custom_file.path, options
  end

  private
  def remove_file?(params)
    if params[:name] == 'conference'
      if params[:conference][:remove_custom_file] == '1'
        true
      end
    end
  end

  # get the page contents when saving a page
  # if page is conference, then join fields, else @contents = content field
  # +params: the parameters from the update form
  def get_contents(params)
    conference = params[:conference]
    if params[:name] == 'conference'
      conference[:date] + '±' + conference[:location] + '±' +
        conference[:conf_name] + '±' + conference[:content]
    else
      params[:static_page][:contents]
    end
  end

  # Get the page file when updating if if one exists
  # +params: contains the parameters from the update form.
  # Returns the file if present
  def get_file(params)
    if params[:name] == 'conference'
      params[:conference][:custom_file]
    else
      params[:static_page][:custom_file]
    end
  end

  # parameters for a static_page
  def static_params
    params.require(:static_page).permit(:name, :contents,
                                        :custom_file,
                                        :custom_file_cache​)
  end

  # Set page by name of page
  def set_page
    @static_page = StaticPage.find_by name: params[:name]
  end
end

app/views/static_pages/_edit_form.html.haml
-# this is the form used to edit the contents of a static page

-# If the current page is the conference page then display the conference form
-# This version of the form includes more sections for title, date, and location
- if @static_page.name == 'conference'
  .modal-dialog
    .modal-content.left-align
      - conference  = @static_page.contents.split('±')
      = simple_form_for :conference, url: static_page_path, method: 'patch', remote: true do |p|
        .modal-header
          %button.close{type: :button, data: {dismiss: :modal}}
            %span &times
          %h4.modal-title Editing #{@static_page.name.titleize} Information
        .modal-body
          -# Form inputs, file_cache maintains file if page is refrehsed.ß
          = p.input :conf_name, input_html: {value: conference[2]}
          = p.input :location, input_html: {value: conference[1]}
          = p.input :date, input_html: {value: conference[0]}
          = p.input :content, as: :wysihtml5, input_html: {value: conference[3]}
          .row
            .col-md-6
              = p.input :custom_file, as: :file
              = p.hidden_field :custom_file_cache
            .col-md-4.col-md-offset-2.right-align
              %label Remove Current File
              = p.check_box :remove_custom_file
        .modal-footer
          = p.button :submit, id: 'submit-btn'

- else
  -# If current page is not conference, then display the standard form
  .modal-dialog.member
    .modal-content.left-align
      = simple_form_for @static_page, remote: true do |p|
        .modal-header
          %button.close{type: :button, data: {dismiss: :modal}}
            %span &times
          %h4.modal-title Editing #{@static_page.name.titleize} Information
        .modal-body
          = p.input :contents, as: :wysihtml5
          .row
            -# Add or remove a custom file
            .col-md-6
              = p.input :custom_file, as: :file
              = p.hidden_field :custom_file_cache
            .col-md-4.col-md-offset-2.right-align
              %label Remove Current File
              = p.check_box :remove_custom_file
        .modal-footer
          = p.button :submit

app/views/static_pages/_file.html.haml
-# Used to render the file of a static page if one is present

-# If the file is an image, then render with a link to the image tag
- if %w{jpg png jpeg gif}.include?(@static_page.custom_file.file.extension)
  = link_to image_tag(show_file_static_page_url(@static_page)),show_file_static_page_path(@static_page)

- else
  -# Else, render as an embedded object. If no embedded object can be created
  -# then display text stating so and providing a link for download
  %object{data: show_file_static_page_url(@static_page) + '//?zoom=50'}
    %p
      It seems you do not have a compatible PDF viewer. Not to worry, please
      = link_to 'click here', download_file_static_page_url(@static_page), target: '_blank'
      to download the file.

app/views/static_pages/_static_contents.html.haml
-# Actually renders the static contents of pages

-# If the page is the 'conference' page, then split the contents
-# and render them in appropriate format
- if @static_page.name == 'conference'
  - conference  = @static_page.contents.split('±')
  %h2 #{conference[0].html_safe}, #{conference[1].html_safe}
  %h3 #{conference[2].html_safe}
  %p=sanitize conference[3].html_safe
- else
  -# Else render as santized html safe output
  %p=sanitize @static_page.contents.html_safe

-# If the static page has a file attached, then render it
-unless @static_page.custom_file.file.nil?
  .row
    .text-center.file
      = render 'file'

-# If the current page is the contact page,
-# Then set the email parameter and then render the contact form
- if @static_page.name == 'contact'
  .row
    - params[:email] = 'dknott1@sheffield.ac.uk'
    = render 'messages/new'

-# If the user is signed in and a web admin, add the edit button for the page
.row.right-align
  - if (user_signed_in?) && (can? :update_static_pages, StaticPage)
    %button.btn.btn-primary{data:{toggle: 'modal', target: '#editModal'}, id: 'edit-btn'}
      Edit

    .modal.fade{id: 'editModal', aria:{hidden: :true}}
      = render 'edit_form'

app/views/static_pages/home.html.haml
-# Used for the home page because it differs so much from other static pages

- content_for :title, "Home"

-# Display the FYN logo and render the static content part of the page
%span
	= image_tag "fyn.jpg", height:'160', alt: 'Foundation Year Network Logo'
	.divider
	.box.left-align
		.page-contents
			= render 'static_contents'

		-# If the user is signed in and a web admin, then allow
		- if (user_signed_in?) && (can? :upload_courses, :uploads)
			- if (user_signed_in?) && (can? :update_static_pages, StaticPage)
				%button.btn.btn-primary{data:{toggle: 'modal', target: '#scrapeModal'}}
					Refresh Database

				.modal.fade{id: 'scrapeModal', aria:{hidden: :true}}
					= render 'courses/scrape'


-# Used to display the twitter feed and search section
.row.search-and-tweet
	-# Search section of the home page
	.col-md-8.page-header.home-search
		- content_for :header, "Search for a Degree with Foundation Year"
		= render 'layouts/search_page_header'


	-# FYN twitter feed
	.box.col-md-4.twitter
		= link_to "Tweets by foundationyear1", 'https://twitter.com/foundationyear1?ref_src=twsrc%5Etfw', :class => 'twitter-timeline'

-# JS for the twitter feed
%script{:async => "", :src =>"https://platform.twitter.com/widgets.js", :charset => "utf-8"}

app/views/static_pages/show.html.haml
-# Used to display a static page

-# Titleize the title and header content and render a standard page header
- content_for :title, @static_page.name.titleize
- content_for :header, @static_page.name.titleize
= render 'layouts/standard_header'

-# Create blog and align content, then render the actual contents
.box.left-align
  .page-contents
    = render 'static_contents'

app/views/static_pages/update_failure.js.haml
-# Re-render edit page, display an error message, and scroll to the top 

$('#modalWindow').html('#{j render template: 'static_pages/edit'}');
$.flashAlert('An Error Occurred. Please Try Again', 'alert-alert');
$(this).scrollTop(0);

app/views/static_pages/update_success.js.haml
-# Hide the modal and remove the backdrop
-# Then re-render the page contents, display a success message
-# and scroll to the top

$('#editmodal').modal('hide');
$('.modal-backdrop').remove();
$('body').removeClass('modal-open')
$(".page-contents").html($('#{j render 'static_contents'}'));
$.flashAlert('Page Successfully Updated', 'alert-notice');
$(this).scrollTop(0);