config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions',  passwords: 'users/passwords'}

  # New routes for devise logging in and registering
  devise_scope :user do
    get :login, to: 'devise/sessions#new', as: 'login'
    post :login, to: 'devise/sessions#create'
    get :register, to: 'users/registrations#new', as: 'registration'
    post :register, to: 'users/registrations#create'
    get :forgotten_password, to: 'users/passwords#new', as: 'forgotten_password'
    post :forgotten_password, to: 'users/passwords#edit'
    get :change_password, to: 'users/registrations#edit', as: 'change_password'
    # post :change_password, to: 'users/registrations#update'
  end

  resources :roles
  resources :institutions
  resources :account_privacies
  resources :departments
  resources :costs
  resources :student_types
  resources :incoming_qualifications
  resources :eligibility_requirements
  resources :end_qualifications
  resources :deliver_modes
  resources :wps
  resources :stored_searches
  resources :courses do
    post :search, on: :collection
  end
  resources :members do
    post :search, on: :collection
  end
  resources :static_pages, except: [:index, :destroy], param: :name, path: 'about' do
     get :show_file, on: :member
     get :download_file, on: :member
  end

  resources :uploads, only: [:new] do
    post :upload_courses, on: :collection
  end
  resources :blogs do
    get :show_file, on: :member
    get :download_file, on: :member
  end

  resource :passwords, only: [:new, :create, :edit, :update] do
    member do
    put :reset
    end
  end


  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  # Add routes for all pages

  get :degree_search, to: 'pages#degree_search', as: 'degree_search'
  get :'degree_search/advanced', to: 'pages#advanced_search', as: 'advanced_search'

  # static pages
  post :'update-static-page', to: 'static_pages#update_static_page', as: 'update_static_page'
  get :'about', to: 'static_pages#about', as: 'about'

  post :'sending', to: 'messages#create', as: 'send_message'
  get :'members/*id/contact', to: 'members#contact', as: 'contact_member'

  get :'members/*id/validate', to: 'members#validate_member', as: 'validate_member'
  post :'members/*id/validate', to: 'members#validate_send'


  root to: 'static_pages#home'

  #stored searches
  get :'create-search', to: 'stored_searches#create_search', as:'create-search'
  get :'save-search', to: 'stored_searches#save_search', as:'save-search'
  get :'delete-search', to: 'stored_searches#delete_search', as:'delete-search'

  get :'scrape', to: 'courses#scrape', as:'scrape-courses'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :bigint(8)        not null, primary key
#  content    :text             not null
#  file       :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  member_id  :bigint(8)        not null
#  privacy_id :bigint(8)        not null
#
# Indexes
#
#  index_blogs_on_member_id   (member_id)
#  index_blogs_on_privacy_id  (privacy_id)
#
# Foreign Keys
#
#  fk_rails_...  (member_id => members.id)
#  fk_rails_...  (privacy_id => privacies.id)
#

class Blog < ApplicationRecord
  mount_uploader :file, BlogFileUploader

  validates :content, presence: true
  validates :name, presence: true
  validates :member_id, presence: true
  validates :privacy_id, presence: true

  belongs_to :member
  belongs_to :privacy
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

# Author:    Team 34: Luke Peacock
# Updated:   20.03.2019

# Controller class for Blog Posts
class BlogsController < ApplicationController
  before_action :set_blogs, only: [:show, :edit, :update,
                                   :destroy, :show_file, :download_file]
  # Set the blog to correct version for all actions listed above

  # new blog
  def new
    @blog = Blog.new
  end

  # create the actual blog record and save it.
  # Then redirect to blog list if success, or show message if not.
  def create
    blog = blog_params
    blog[:member_id] = current_user.member_id
    # if blog is valid (i.e. has name and content), create it
    if valid_blog(blog[:name], blog[:content], current_user)
      @blog = Blog.new(blog)
      if @blog.save
        redirect_to blogs_path, notice: 'Blog post successfully created'
        return
      end
    end
    render 'creation_failure'
  end

  # show all blogs, sort them based on user choice (default last active),
  # and then paginate and render view
  def index
    # CanCanCan authorization
    authorize! :read, :pages
    @current_nav_identifier = :blogs
    # Get all blogs if user is member, or just public ones if not signed in
    @blogs = if user_signed_in? && current_user.member.role.name != "Pending"
               Blog.all
             else
               Blog.where('privacy_id = 1')
             end
    # sort the blogs based on user choice
    @blogs = case params[:sort]
             when 'Name Alphabetical Ascending'
               @blogs.order('name ASC')
             when 'Name Alphabetical Descending'
               @blogs.order('name DESC')
             when 'Most Recent'
               @blogs.order('created_at DESC')
             else
               @blogs.order('updated_at DESC')
             end
    # paginate results
    @blogs = @blogs.page(params[:page]).per_page(10)
  end

  # show blog post
  def show; end



  # method to update an existing blog - checks parameters first
  def update
    if @blog.update(blog_params)
      render 'update_success'
    else
      render 'update_failure'
    end
  end

  # delete a blog from the database, then redirect to blog list
  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: 'Blog was successfully deleted'
  end

  # download a file to the user's computer
  # all files are named 'download.extension'
  def download_file
    options = { type: @blog.file.file.content_type,
                disposition: 'attachment; filename="' + @blog.file.path.split("/").last + '"',
                url_based_filename: true }
    send_file(@blog.file.file.path, options)
  end

  # pass the blog file to the view so that it can be shown to the user
  def show_file
    options = { type: @blog.file.file.content_type,
                disposition: 'inline' }
    send_file @blog.file.path, options
  end

  private

  # function to check blog has a name and content
  def valid_blog(name, content, current_user)
    return false if current_user.member.role.name == "Pending"
    return false if name.nil? || name == ''
    return false if content.nil? || content == ''
    true
  end

  # Set the blog based on ID provided
  def set_blogs
    @blog = Blog.find(params[:id])
  end

  # Authorized blog parameters
  def blog_params
    params.require(:blog).permit(:name, :content, :file, :file_cache,
                                 :member_id, :privacy_id, :remove_file)
  end
end

app/views/blogs/_blog_entry.html.haml
-# This partial shows the actual blog contents.
-# It will show the sanitized blog content, file is applicable
-# Then author name, institute, created and updated times,


.container.content.left-align
  = sanitize @blog.content.html_safe
-unless @blog.file.file.nil?
  .text-center.file
    = render 'file'
.container.content.left-align
  .divider
  .author_info
    %table
      %tr
        %td.info
          %b Written By:
        %td
          =link_to @blog.member.name, @blog.member
      %tr
        %td.info
          %b Author's Institution:
        %td= @blog.member.institution.name
      %tr
        %td.info
          %b Created At:
        %td= l(@blog.created_at, format: :compact_time)
      %tr
        %td.info
          %b Last Updated:
        %td= l(@blog.updated_at, format: :compact_time)


  -# If the user is signed in and owns the blog or
  -# is university admin for the institute, or web admin
  -# add the ability to edit and delete the blog post
  - if (user_signed_in?)
    -if ((@blog.member.user.email == current_user[:id]) || ((current_user.member.institution_id == @blog.member.institution_id) && (current_user.member.role.name == 'University Admin')) || (current_user.member.role.name == 'Website Admin'))
      .buttons.right-align
        = link_to 'Delete Post', @blog, method: :delete, data: {confirm: 'Are You Sure?'}, class: 'btn btn-primary'

        %button.btn.btn-primary{data:{toggle: 'modal', target: '#editModal'}}
          Edit

        .modal.fade{id: 'editModal', aria:{hidden: :true}}
          = render 'edit'

app/views/blogs/_blog_header.html.haml
-# This is the header file for the blog entries
-# Shows blog name and updated date


.page-header
  %h3 #{content_for(:header_name)}
  %h5.right-align Last Updated: #{content_for(:header_date)}

app/views/blogs/_blog_list.html.haml
-# This will render each blog in the index
-# Shows member name, member institute, blog created and updated times,
-# And truncated content preview, plus button to view entry


- @blogs.each do |b|
  .row.box.index-list
    .row
      .left-align.col-md-3
        %h3.name= truncate(b.name, length: 50, escape: false)
        %h4.institute= b.member.name
        %h6 Updated: #{l(b.updated_at, format: :compact)}
        %h5 Created: #{l(b.created_at, format: :compact)}
      .left-align.content.col-md-7= sanitize truncate(b.content, length: 200, escape: false)
      .col-md-2
        = link_to 'View Post', b,:class => 'btn btn-secondary view-btn'

app/views/blogs/_edit.html.haml
.modal-dialog.modal-lg.left-align
  -# This view is opened a modal and used to render the edit form
  .modal-content
    .modal-header
      %h3.modal-title Edit this Blog
      %button.close{data:{dismiss:'modal'}}
        %span &times;
    .modal-body
      =render 'form'

app/views/blogs/_file.html.haml
-# This view is used to render the file attached to a blog if applicable
-# If file is an image then render link to image tag
-# if file is not image, then render embedded object
-# if no embedded object can be displayed, show error message and download link


- if %w{jpg png jpeg gif}.include?(@blog.file.file.extension)
  = link_to image_tag(show_file_blog_url(@blog)),download_file_blog_url(@blog)
- else
  %object{data: show_file_blog_url(@blog) + '/?zoom=50'}
    %p
      It seems you do not have a compatible PDF viewer. Not to worry, please
      = link_to 'click here', download_file_blog_url(@blog), target: '_blank'
      to download the file.

app/views/blogs/_form.html.haml
= simple_form_for @blog, remote: true do |f|
  -# This view is the edit form for a blog post
  -# Renders ability to add name, content and file to a post
  -# and if editing, remove a current file
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-input
    .right-align
      %label
        %abbr{title: 'required'}*
        Privacy Setting:
      = f.select :privacy_id, Privacy.all.map { |p| [p.level, p.id] }
    = f.input :name, required: true
    = f.input :content, as: :wysihtml5,  required: true
    .row
      .col-md-6
        = f.input :file, as: :file
        = f.hidden_field :file_cache
      - unless @blog.name.nil?
        .col-md-4.col-md-offset-2.right-align
          %label Remove Current File
          = f.check_box :remove_file

  .form-actions.right-align
    = f.button :submit

app/views/blogs/creation_failure.js.haml
-# This view will render an error and scroll to the top of the page
-# Used when an error occurs while creating a new blog post

$.flashAlert('An Error Occurred. Please Try Again', 'alert-alert');
$('.btn btn-default').removeAttr('disabled');
$(this).scrollTop(0);

app/views/blogs/index.html.haml
-# This view is used to display the blog index,
-# renders the blog_list partial

- content_for :title, "Blogs"
- content_for :header, "Blogs"
= render 'layouts/blogs_index_header'

.blog-list
  - if !@blogs.nil?
    = render 'blog_list'
  - else
    .box
      %h5 No Blogs Found

app/views/blogs/new.html.haml
-# This view is used to create a new blog post
-# Renders the form

- content_for :title, "New Blog"
- content_for :header, "New Blog"
= render 'layouts/standard_header'

.box.blog
  .container.content.left-align
    = render 'form'

app/views/blogs/show.html.haml
-# This view is used to show the blog
-# displays blog if blog is public, or member is logged in
-# else redirects back to blog index


- if @blog.privacy_id == 1 || ((user_signed_in?) && (can? :read, Blog))
  - content_for :title, "#{@blog[:name]}"
  - content_for :header_name, @blog.name
  - content_for :header_date, l(@blog.updated_at, format: :compact_time)
  = render 'blog_header'

  .box.blog
    = render 'blog_entry'
- else
  redirect_to blogs_path

app/views/blogs/update_failure.js.haml
-# This will re-render the edit form, display an error message,
-# and scroll to the top

$('#modalWindow').html('#{j render template: 'blogs/edit'}');
$.flashAlert('An Error Occurred. Please Try Again', 'alert-alert');
$(this).scrollTop(0);

app/views/blogs/update_success.js.haml
-# This will close the modal window, re-render the blog contents,
-# Display a success message, and scroll to the top of the window

$('#modalWindow').modal('hide');
$('.modal-backdrop').remove();
$('body').removeClass('modal-open')
$(".blog").html($('#{j render 'blog_entry'}'));
$.flashAlert('Blog Successfully Updated', 'alert-notice');
$(this).scrollTop(0);