config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions',  passwords: 'users/passwords'}

  # New routes for devise logging in and registering
  devise_scope :user do
    get :login, to: 'devise/sessions#new', as: 'login'
    post :login, to: 'devise/sessions#create'
    get :register, to: 'users/registrations#new', as: 'registration'
    post :register, to: 'users/registrations#create'
    get :forgotten_password, to: 'users/passwords#new', as: 'forgotten_password'
    post :forgotten_password, to: 'users/passwords#edit'
    get :change_password, to: 'users/registrations#edit', as: 'change_password'
    # post :change_password, to: 'users/registrations#update'
  end

  resources :roles
  resources :institutions
  resources :account_privacies
  resources :departments
  resources :costs
  resources :student_types
  resources :incoming_qualifications
  resources :eligibility_requirements
  resources :end_qualifications
  resources :deliver_modes
  resources :wps
  resources :stored_searches
  resources :courses do
    post :search, on: :collection
  end
  resources :members do
    post :search, on: :collection
  end
  resources :static_pages, except: [:index, :destroy], param: :name, path: 'about' do
     get :show_file, on: :member
     get :download_file, on: :member
  end

  resources :uploads, only: [:new] do
    post :upload_courses, on: :collection
  end
  resources :blogs do
    get :show_file, on: :member
    get :download_file, on: :member
  end

  resource :passwords, only: [:new, :create, :edit, :update] do
    member do
    put :reset
    end
  end


  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  # Add routes for all pages

  get :degree_search, to: 'pages#degree_search', as: 'degree_search'
  get :'degree_search/advanced', to: 'pages#advanced_search', as: 'advanced_search'

  # static pages
  post :'update-static-page', to: 'static_pages#update_static_page', as: 'update_static_page'
  get :'about', to: 'static_pages#about', as: 'about'

  post :'sending', to: 'messages#create', as: 'send_message'
  get :'members/*id/contact', to: 'members#contact', as: 'contact_member'

  get :'members/*id/validate', to: 'members#validate_member', as: 'validate_member'
  post :'members/*id/validate', to: 'members#validate_send'


  root to: 'static_pages#home'

  #stored searches
  get :'create-search', to: 'stored_searches#create_search', as:'create-search'
  get :'save-search', to: 'stored_searches#save_search', as:'save-search'
  get :'delete-search', to: 'stored_searches#delete_search', as:'delete-search'

  get :'scrape', to: 'courses#scrape', as:'scrape-courses'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_blogs_index_header.html.haml
-# Used as the header of the blogs index
-# Displays blog ordering choice
-# And ability to create a new blog if the user is signed in
-# also shows pagination options for changing pages

.page-header
  %h3 #{content_for(:header)}

  .row.header-content
    %form{:action => request.fullpath, :method => 'get', :class =>'simple-form ', remote: true}
      %span.col-md-8.col-md-offset-4.no-padding.search-input
        %label Order By:
        = select_tag :sort,
            options_for_select([ "Last Updated", "Most Recent","Name Alphabetical Ascending",
                                  "Name Alphabetical Descending"], params[:sort]),
                                class: 'sort',
                                onchange: 'this.form.submit()'
        .col-md-4.col-md-offset-2
          = submit_tag 'Submit', style: 'visibility: hidden', class: 'submit-btn'
    - if (user_signed_in? && current_user.member.role != 4)
      = link_to new_blog_path, method: :get, title: "New", :class => 'new-blog btn btn-secondary' do
        New Blog
  .row
    .col-md-4.left-align
      .digg_pagination
        .page_info
          = page_entries_info @blogs
    .col-md-4.col-md-offset-4.right-align
      = will_paginate @blogs,
        previous_label: '<i class ="fa fa-caret-left"></i>',
        next_label: '<i class ="fa fa-caret-right"></i>'

app/views/layouts/_environment_notice.html.haml
- if display_environment_notice?
  .environment-notice.alert.alert-info
    %strong Notice:
    This is the
    %strong= Rails.env
    system.

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  - next unless name == 'alert' || name == 'notice'
  .alert.fade.in
    .container
      - if name == 'notice'
        = fa_icon('check', class: 'flash-success')
      - else
        = fa_icon('warning', class: 'flash-error')
      = msg
      %a{ href: '#', title: 'Hide this message', data: { dismiss: :alert } } Dismiss

app/views/layouts/_members_page_header.html.haml
-# Members index header
-# shows ability to search results, sort them, and pagination options

.page-header
  %h3 #{content_for(:header)}

  .row.header-content
    %form{:action => request.fullpath, :method => 'get', :class =>'simple-form '}
      = hidden_field_tag :institute, nil, value: params[:institute]
      = hidden_field_tag :role, nil, value: params[:role]
      %span.col-md-6.col-md-offset-4.no-padding.search-input
        = text_field_tag :search, nil, :placeholder => 'Search Members' , value: params[:search], :class => 'search-term'
      .search
        %button{:type =>"submit", :class => 'btn btn-secondary', id: 'search-btn'}
          .fa.fa-search
          Search
      %span.col-md-6.col-md-offset-4.no-padding.search-input
        %label Order By:
        = select_tag :sort,
            options_for_select([ "Last Active", "Name Alphabetical Ascending",
                                  "Name Alphabetical Descending"], params[:sort]),
                                class: 'sort',
                                onchange: 'this.form.submit()'

  .row
    .col-md-4.left-align
      .digg_pagination
        .page_info
          = page_entries_info @members
    .col-md-4.col-md-offset-4.right-align
      = will_paginate @members,
        previous_label: '<i class ="fa fa-caret-left"></i>',
        next_label: '<i class ="fa fa-caret-right"></i>'

app/views/layouts/_search_page_header.html.haml
-# Search Page header
-# Ability to search by name/subject and/or institute/location
-# Also includes pagination results, and ability to save a search

.page-header
  %h3 #{content_for(:header)}
  .header-content
    = form_tag courses_path, :method => 'get', novalidate: 'novalidate', :class =>'simple-form' do
      - home = false
      - home = true if content_for(:title) == 'Home'
      -classes = [("col-md-8" unless home), "no-padding search-input", ("left-align" if home)]
      %span{class: classes}
        = text_field_tag :subject, nil, value: params[:subject], :placeholder => 'Subject or Degree', :class => 'search-term'
        %label and/or
        = text_field_tag :location, nil, value: params[:location], :placeholder => 'Institute or Location', :class => 'search-term'
      .search
        %button{:type =>"submit", :class => 'btn btn-secondary'}
          .fa.fa-search
          Search
        = link_to "Advanced Search", advanced_search_path, title: "Go to Advanced Search page"
  -if content_for(:header) == 'Courses'
    .row
      .col-md-4.left-align
        .digg_pagination
          .page_info
            = page_entries_info @course
      .col-md-4.col-md-offset-4.right-align
        = will_paginate @courses,
          previous_label: '<i class ="fa fa-caret-left"></i>',
          next_label: '<i class ="fa fa-caret-right"></i>',
          inner_window: 5,
          outer_window: 0
  -elsif content_for(:title) == 'Degree Search'
    .row

  = form_tag "create-search", :method => 'get', :class => 'simple-form' do
    = hidden_field_tag :subject, value = params[:subject]
    = hidden_field_tag :institution, value = params[:institution]
    = hidden_field_tag :full_time, value = params[:full_time]
    = hidden_field_tag :duration, value = params[:duration]
    = hidden_field_tag :distance, value = params[:distance]
    = hidden_field_tag :location, value = params[:location]

    .save_search
      %button{:type => "submit", :class => 'btn btn-secondary'}
        .fa.fa-save
        Save Search

app/views/layouts/_standard_header.html.haml
-# Standard page header, just shows page title

.page-header
  %h3 #{content_for(:header)}

app/views/layouts/application.html.haml
!!!
-# Main application layout
-# Includes meta options, flash message and environment settings
-# Includes header and footer content
%html
  %head
    %title FYN - #{content_for(:title)}
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "content-type"}
    = stylesheet_link_tag    "application", media: :all
    = javascript_include_tag "application"
    = favicon_link_tag '/favicon.ico'
    = csrf_meta_tags

  %body{ class: environment_notice_body_class }
    = render 'layouts/environment_notice'
    .flash-messages
      - flash.each do |name, msg|
        - next unless name == 'alert' || name == 'notice'
        .alert.fade.in
          .container
            - if name == 'notice'
              = fa_icon('check', class: 'flash-success')
            - else
              = fa_icon('warning', class: 'flash-error')
            = msg
            %a{ href: '#', title: 'Hide this message', data: { dismiss: :alert } } Dismiss


    %noscript
      .warning-page-cover
        .alert.alert-info
          %h2 Sorry, it appears that you are using a web browser without JavaScript which prevents us offering you a rich online experience.
          %p Please enable JavaScript or use a different web browser, or alternatively contact the CiCS Helpdesk for assistance.

    %nav#main-nav.navbar.navbar.navbar-default{role: :navigation}
      .navbar-header
        %button.navbar-toggle{ data: { target: ".navbar-collapse", toggle: :collapse}, type: :button}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        =link_to :root, title: "Go to the home page", identifier: :home, :class=>'navbar-brand' do
          =image_tag "fyn.jpg", height:'80', alt: 'Foundation Year Network Logo'

      .collapse.navbar-collapse
        %ul.navbar-nav.navbar-right
          = navbar_link_to 'Home',:root, title: "Go to the home page", :class => 'nav-item nav-link'
          = navbar_link_to 'Degrees', degree_search_path, title: "Go to Degree Search Page", :class => 'nav-item nav-link'
          = navbar_link_to 'Conference',static_page_path('conference'), title: "Go to Conference Page", :class => 'nav-item nav-link'
          %li.dropdown
            .dropdown-toggle.disabled{data: {toggle:'dropdown'}}
              = link_to 'About', about_path, title: "About Us", :class => 'nav-item nav-link', role: 'hover'
              %span.caret
            %ul.dropdown-menu.dropdown-menu-left
              = navbar_link_to 'Constitution',static_page_path('constitution'), title: "Go our constitution page", :class => 'nav-item nav-link'
              = navbar_link_to 'Blog',blogs_path, title: "Go to our blogs page", :class => 'nav-item nav-link'
              = navbar_link_to 'Members',members_path, title: "Go to our members", :class => 'nav-item nav-link'
              = navbar_link_to 'Get Involved',static_page_path('get_involved'), title: "Learn how to get involved", :class => 'nav-item nav-link'
              = navbar_link_to 'Contact Us',static_page_path('contact'), title: "Find out how to contact us", :class => 'nav-item nav-link'
              = navbar_link_to 'Privacy Policy',static_page_path('privacy_policy'), title: "Read our privacy policy", :class => 'nav-item nav-link'
          = navbar_link_to 'Help',static_page_path('help'), title: "Go to Help Page", :class => 'nav-item nav-link'

          - if user_signed_in?
            %li.dropdown
              .dropdown-toggle.disabled.user-dropdown{data: {toggle:'dropdown'}}
                = link_to member_path(@current_user.member), title: 'View your profile', class: 'nav-item nav-link' do
                  = fa_icon 'user', text: current_user.member.name
                %span.caret
              %ul.dropdown-menu.dropdown-menu-right.login-dropdown
                %li
                  = link_to destroy_user_session_path, method: :delete, title: "Log out", class: 'nav-item nav-link' do
                    = fa_icon 'sign-out', text: 'Log Out'
          -else
            %li.login
              = link_to 'Login', login_path, title: "go to Login Page", :class => 'login-button btn btn-primary'


          -# - if user_signed_in?
            -#   %ul.nav.navbar-nav.navbar-right
            -#     %li.dropdown
            -#       = link_to '#', data: { toggle: :dropdown }, class: 'dropdown-toggle', role: 'button', 'aria-haspopup' => true, 'aria-expanded' => false do
            -#         = fa_icon 'user', text: current_user.email
            -#         %b.caret
            -#       %ul.dropdown-menu
            -#         %li
            -#           = link_to destroy_user_session_path, method: :delete, title: "Log out of the system" do
            -#             = fa_icon 'sign-out', text: 'Log out'
    #wrap
      = yield

    %footer#footer
      =link_to "News", blogs_path, :class => 'footer-link'
      =link_to "Contact", static_page_path('contact'), :class => 'footer-link'
      =link_to "About", about_path, :class => 'footer-link'
      =link_to "Get Involved", static_page_path('get_involved'), :class => 'footer-link'
      =link_to "Privacy Policy", static_page_path('privacy_policy'), :class => 'footer-link'
      %p.footer-copyright
        &copy;#{Date.today.year} Foundation Year Network &
        = link_to 'University of Sheffield', 'https://www.sheffield.ac.uk', target: '_blank', title: 'Goto University of Sheffield website'
        students: Luke Peacock, Seth Faulkner, Mathew Prestwich, Dean Knott, Luke Markie

app/views/layouts/plain_error.html.haml
!!!
%html
  %head
    %title Test-project - #{content_for(:title)}
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    = stylesheet_link_tag    "application", media: :all
    = javascript_include_tag "application"
    = favicon_link_tag '/favicon.ico'

  %body{ class: environment_notice_body_class }
    = render 'layouts/environment_notice'
    .flash-messages
      - flash.each do |name, msg|
        - next unless name == 'alert' || name == 'notice'
        .alert.fade.in
          .container
            - if name == 'notice'
              = fa_icon('check', class: 'flash-success')
            - else
              = fa_icon('warning', class: 'flash-error')
            = msg
            %a{ href: '#', title: 'Hide this message', data: { dismiss: :alert } } Dismiss


    %noscript
      .warning-page-cover
        .alert.alert-info
          %h2 Sorry, it appears that you are using a web browser without JavaScript which prevents us offering you a rich online experience.
          %p Please enable JavaScript or use a different web browser, or alternatively contact the CiCS Helpdesk for assistance.

     %nav#main-nav.navbar.navbar.navbar-default
      .navbar-header
        %button.navbar-toggle{ data: { target: ".navbar-collapse", toggle: :collapse}, type: :button}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        =link_to :root, title: "Go to the home page", identifier: :home, :class=>'navbar-brand' do
          =image_tag "fyn.jpg", height:'80', alt: 'Foundation Year Network Logo'

      .collapse.navbar-collapse
        %ul.navbar-nav.navbar-right
          = navbar_link_to 'Home',:root, title: "Go to the home page", :class => 'nav-item nav-link'
          = navbar_link_to 'Degrees', '/degree_search', title: "Go to Degree Search Page", :class => 'nav-item nav-link'
          = navbar_link_to 'Conference','/conference', title: "Go to Conference Page", :class => 'nav-item nav-link'
          %li.dropdown
            .dropdown-toggle
              = navbar_link_to 'About', "/about", title: "About Us", :class => 'dropdown-toggle nav-item nav-link', data:{toggle:'dropdown'}, role: 'hover'
              %span.caret
            %ul.dropdown-menu.dropdown-menu-left
              = navbar_link_to 'Constitution',"/about/constitution", title: "Go our constitution page", :class => 'nav-item nav-link'
              = navbar_link_to 'News',"/news", title: "Go to our news page", :class => 'nav-item nav-link'
              = navbar_link_to 'Members',"/members", title: "Go to our members", :class => 'nav-item nav-link'
              = navbar_link_to 'Get Involved',"/about/get-involved", title: "Learn how to get involved", :class => 'nav-item nav-link'
              = navbar_link_to 'Contact Us',"/about/contact-us", title: "Find out how to contact us", :class => 'nav-item nav-link'
              = navbar_link_to 'Privacy Policy',"/about/privacy-policy", title: "Read our privacy policy", :class => 'nav-item nav-link'

          = navbar_link_to 'Help',"/help", title: "Go to Help Page", :class => 'nav-item nav-link'
          %li.login
            %button.btn.btn-primary.login-button{action: '/login', title: 'Go to login page'}
              Login

          -# - if user_signed_in?
            -#   %ul.nav.navbar-nav.navbar-right
            -#     %li.dropdown
            -#       = link_to '#', data: { toggle: :dropdown }, class: 'dropdown-toggle', role: 'button', 'aria-haspopup' => true, 'aria-expanded' => false do
            -#         = fa_icon 'user', text: current_user.email
            -#         %b.caret
            -#       %ul.dropdown-menu
            -#         %li
            -#           = link_to destroy_user_session_path, method: :delete, title: "Log out of the system" do
            -#             = fa_icon 'sign-out', text: 'Log out'
    #wrap
      = yield

    %footer#footer
      .container
        %p
          &copy;#{Date.today.year}
          = link_to 'epiGenesys', 'https://www.epigenesys.org.uk', target: '_blank', title: 'Goto the epiGenesys website'