config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions',  passwords: 'users/passwords'}

  # New routes for devise logging in and registering
  devise_scope :user do
    get :login, to: 'devise/sessions#new', as: 'login'
    post :login, to: 'devise/sessions#create'
    get :register, to: 'users/registrations#new', as: 'registration'
    post :register, to: 'users/registrations#create'
    get :forgotten_password, to: 'users/passwords#new', as: 'forgotten_password'
    post :forgotten_password, to: 'users/passwords#edit'
    get :change_password, to: 'users/registrations#edit', as: 'change_password'
    # post :change_password, to: 'users/registrations#update'
  end

  resources :roles
  resources :institutions
  resources :account_privacies
  resources :departments
  resources :costs
  resources :student_types
  resources :incoming_qualifications
  resources :eligibility_requirements
  resources :end_qualifications
  resources :deliver_modes
  resources :wps
  resources :stored_searches
  resources :courses do
    post :search, on: :collection
  end
  resources :members do
    post :search, on: :collection
  end
  resources :static_pages, except: [:index, :destroy], param: :name, path: 'about' do
     get :show_file, on: :member
     get :download_file, on: :member
  end

  resources :uploads, only: [:new] do
    post :upload_courses, on: :collection
  end
  resources :blogs do
    get :show_file, on: :member
    get :download_file, on: :member
  end

  resource :passwords, only: [:new, :create, :edit, :update] do
    member do
    put :reset
    end
  end


  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get :javascript_warning, to: 'errors#javascript_warning'

  # Add routes for all pages

  get :degree_search, to: 'pages#degree_search', as: 'degree_search'
  get :'degree_search/advanced', to: 'pages#advanced_search', as: 'advanced_search'

  # static pages
  post :'update-static-page', to: 'static_pages#update_static_page', as: 'update_static_page'
  get :'about', to: 'static_pages#about', as: 'about'

  post :'sending', to: 'messages#create', as: 'send_message'
  get :'members/*id/contact', to: 'members#contact', as: 'contact_member'

  get :'members/*id/validate', to: 'members#validate_member', as: 'validate_member'
  post :'members/*id/validate', to: 'members#validate_send'


  root to: 'static_pages#home'

  #stored searches
  get :'create-search', to: 'stored_searches#create_search', as:'create-search'
  get :'save-search', to: 'stored_searches#save_search', as:'save-search'
  get :'delete-search', to: 'stored_searches#delete_search', as:'delete-search'

  get :'scrape', to: 'courses#scrape', as:'scrape-courses'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id                 :bigint(8)        not null, primary key
#  bio                :text
#  job                :string
#  name               :string           not null
#  title              :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  account_privacy_id :bigint(8)        not null
#  bio_privacy_id     :bigint(8)        not null
#  email_privacy_id   :bigint(8)        not null
#  institution_id     :bigint(8)        not null
#  job_privacy_id     :bigint(8)        not null
#  role_id            :bigint(8)        not null
#
# Indexes
#
#  index_members_on_account_privacy_id  (account_privacy_id)
#  index_members_on_bio_privacy_id      (bio_privacy_id)
#  index_members_on_email_privacy_id    (email_privacy_id)
#  index_members_on_institution_id      (institution_id)
#  index_members_on_job_privacy_id      (job_privacy_id)
#  index_members_on_role_id             (role_id)
#
# Foreign Keys
#
#  fk_rails_...  (account_privacy_id => account_privacies.id)
#  fk_rails_...  (institution_id => institutions.id)
#  fk_rails_...  (role_id => roles.id)
#

class Member < ApplicationRecord
  validates :name, presence: true
  validates :account_privacy_id, presence: true
  validates :bio_privacy_id, presence: true
  validates :email_privacy_id, presence: true
  validates :institution_id, presence: true
  validates :job_privacy_id, presence: true
  validates :role_id, presence: true

  belongs_to :institution
  belongs_to :role
  belongs_to :account_privacy

  belongs_to :email_privacy, :class_name => 'Privacy'
  belongs_to :bio_privacy, :class_name => 'Privacy'
  belongs_to :job_privacy, :class_name => 'Privacy'

  has_many :blog
  has_many :privacies
  has_one :user

end

app/controllers/members_controller.rb
# frozen_string_literal: true

# Author:    Team 34: Luke Peacock
# Updated:   10.03.2019

# controller class for members
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy,
                                    :validate_member, :validate_send, :contact]
  # Set member record to correct member for all actions listed above

  # Search all member records using the search params, then paginate the results
  # and sort them based on user choice (default last active)
  def index
    @current_nav_identifier = :members
    members = search(params)
    members = case params[:sort]
              when 'Name Alphabetical Ascending'
                members.order('name ASC')
              when 'Name Alphabetical Descending'
                members.order('name DESC')
              else
                members.joins(:user).order('users.last_sign_in_at DESC')
              end
    @members = members.page(params[:page]).per_page(10)
  end

  # show individual member profile
  def show; end

  # delete a member and associated user from the database
  def destroy
    destroy_blogs(@member.id)
    @member.user.destroy
    @member.destroy
    redirect_to members_url, notice: 'Member Was Successfully Deleted.'
  end

  # method to view form to validate a member
  def validate_member
    render layout: false
  end

  # method to actually change authorisation level
  def validate_send
    if @member.update(role_id: params[:auth][:role])
      render 'update_success'
    else
      render 'update_failure'
    end
  end

  # render view for the form to edit the member profile
  # layout not rendered since form is displayed as modal
  def edit
    render layout: false
  end

  # Method to save the update to the member record
  def update
    if name_exists(params[:member][:name])
      if @member.update(member_params)
        render 'update_success'
        return
      end
    end
    render 'update_failure'
  end

  # Render view for form to send an email
  # layout is not rendered since contact form is displayed as modal
  def contact
    render layout: false
  end

  private

  # Private function for getting a specific members record
  def set_member
    @member = Member.find(params[:id])
  end

  # Valid member parameters
  def member_params
    params.require(:member).permit(:title, :name, :job, :bio,
                                   :account_privacy_id, :email_privacy_id,
                                   :bio_privacy_id, :job_privacy_id)
  end

  # Check is the member's name exists when updating
  def name_exists(name)
    return false if name.nil? || name == ''

    true
  end

  # Move all blogs posted by an account to the admin account
  # +member_id: the ID of the member begin deleted
  def destroy_blogs(member_id)
    blogs = Blog.where(member_id: member_id)
    admin = Member.where(name: 'Website Admin').first
    blogs.each do |b|
      Blog.where(id: b.id).update(member_id: admin.id)
    end
  end

  # Search method, search name, job, bio, and institute name
  # +params: these are the parameters from the search form, they include
  # search, role, and institue
  # Returns: a subset of Members table matching search criteria
  def search(params)
    # pull out search term, institute, and role
    search = params[:search]
    institute = params[:institute]
    role = params[:role]

    # initialise query string and placeholder hash
    query = []
    placeholders = {}

    # if a search term is present, append query for name, institution name,
    # bio, and job search like search term. Add search term to placeholder hash
    unless search.nil? || search == ''
      query.append('(members.name ILIKE :s OR institutions.name ILIKE :s OR ' \
                   'job ILIKE :s OR bio ILIKE :s)')
      placeholders[:s] = '%' + search + '%'
    end

    # If filtering by institute too, append the query string and add institute
    # to placeholder hash
    unless institute == '' || institute.nil?
      query.append('institution_id = :institute')
      placeholders[:institute] = institute
    end

    # if filtering by role, append the query string an add role to placeholder
    # hash
    unless role == '' || role.nil?
      query.append('role_id = :role')
      placeholders[:role] = role
    end

    # Apply query, with placeholders, and return result
    Member.joins(:institution).references(:institution).joins(:user)
          .references(:user).where(query.join(' AND '), placeholders).all
  end
end

app/views/members/_member_profile.html.haml
-# This view is used to display the members profile


-# Initialise variables to false
- job_viewable = false
- email_viewable = false
- bio_viewable = false

-# If user is signed in and viewing own profile, set all booleans to true
-# else if signed in and privacy is member, set boolean to true
- if user_signed_in?
  - if @member.user.email == current_user[:id]
    - email_viewable = true
    - job_viewable = true
    - bio_viewable = true
  -elsif current_user.member.role.name != "Pending"
    -if @member.job_privacy_id == 2
      - job_viewable = true
    -if @member.email_privacy_id == 2
      - email_viewable = true
    -if @member.bio_privacy_id == 2
      - bio_viewable = true

-# If member has privacy settings as public, set booleans as public
-if @member.email_privacy_id == 1
  -email_viewable = true
-if @member.job_privacy_id == 1
  -job_viewable = true
-if @member.bio_privacy_id == 1
  -bio_viewable = true


-# Initialise edit booleans
- update_member = false
- auth_access = false
-# If user signed in and on own profile, or web admin, set edit boolean as true
-if user_signed_in?
  -if @member.user.email == current_user[:id]
    -update_member = true
  -elsif (can? :update, Member)
    - update_member = true

  -# If user signed in and web admin then set auth boolean as true
  -if (can? :validate, Member) && @member.user.email != current_user[:id]
    -auth_access = true

  -# If user is a university admin for the member's institution
  -# set auth and update booleans as true
  -if current_user.member.role.name == 'University Admin' && current_user.member.institution_id == @member.institution.id
    - auth_access = true
    -update_member = true


-# Begin actual rendering
-# Show name
.row.member-profile
  .row.name.left-align
    %h3 Name:
    %h4= @member.name

  -# show job if job_viewable is true
  -if job_viewable
    .row.job.left-align
      %h3 Position:
      %h4= @member.job

  -# show institution
  .row.institute.left-align
    %h3 Institution:
    %h4= @member.institution.name

  -# Show email is email_viewable is true
  -if email_viewable
    .row.email.left-align
      %h3 Email Address:
      %h4= @member.user.email

  -# render divider, and bio if bio_viewable is true
  .divider
  -if bio_viewable
    .row.bio.left-align
      %h1 Biography:
      %p=sanitize @member.bio.html_safe


  -# if the members email is viewable, display a contact button
  .row.buttons
    -if email_viewable
      .left-align
        .btn.btn-primary.no-padding.link= link_to 'Contact', contact_member_path(@member), class: 'ajax-modal'

    -# if update member is true, show edit and delete buttons for member
    -# if auth_access is true, show authorisation button
    .right-align
      - if update_member
        -if @member.role.name != 'Website Admin' || (@member.role.name == 'Website Admin' && current_user.member.id == @member.id)
          - if current_user.member.role_id <= @member.role_id
            = link_to 'Delete Account', @member, method: :delete, data: {confirm: 'Are You Sure?'}, class: 'btn btn-primary'
          .btn.btn-primary.no-padding.link= link_to 'Edit', edit_member_path(@member) + '/', class: 'ajax-modal'
          .btn.btn-primary.no-padding.link= link_to 'Change Password', change_password_path(@member) + '/', class: 'ajax-modal'


      -if auth_access
        .btn.btn-primary.no-padding.link= link_to 'Change Authorisation', validate_member_path(@member), class: 'ajax-modal'

app/views/members/contact.html.haml
-# Partial used to render the contact form

.modal-dialog
  .modal-content.left-align
    .modal-header
      %h3.modal-title Contact #{@member.name}
      %button.close{data:{dismiss:'modal'}}
        %span
          &times;
    .modal-body
      - params[:email] = @member.user.email
      = render 'messages/new'

app/views/members/edit.html.haml
-# Partial used to display the edit form for members
-# Ability to edit member email privacy, name job, job privacy
-# bio, bio_privacy

.modal-dialog.member
  .modal-content.left-align
    = simple_form_for @member, remote: true do |m|
      .modal-header
        %button.close{type: :button, data: {dismiss: :modal}}
          %span &times
        %h4.modal-title Editing Member Profile
      .modal-body
        .privacy.right-align
          = m.input :email_privacy_id, collection: Privacy.all,
                                     label_method: :level,
                                     value_method: :id,
                                     selected: @member.email_privacy_id,
                                     required: true
        = m.input :title, collection: ['Mr', 'Mrs', 'Ms', 'Miss', 'Dr', 'Prof.'],
                          selected: @member.title,
                          include_blank: false
        = m.input :name, required: true
        = m.input :job
        .privacy.right-align
          = m.input :job_privacy_id, collection: Privacy.all,
                                     label_method: :level,
                                     value_method: :id,
                                     selected: @member.job_privacy_id,
                                     required: true
        = m.input :bio, as: :wysihtml5, label: 'Biography'
        .privacy.right-align
          = m.input :bio_privacy_id, collection: Privacy.all,
                                     label_method: :level,
                                     value_method: :id,
                                     selected: @member.bio_privacy_id,
                                     required: true
          = m.association :account_privacy, as: :hidden
      .modal-footer
        = m.button :submit

app/views/members/index.html.haml
-# View used to display a list of members

- content_for :title, "Members"
- content_for :header, "Members"
= render 'layouts/members_page_header'

-unless @members.empty? || @members.nil?
  -# Filters for the page, including institute, role, search field, and order
  %button.btn.btn-primary{data:{toggle: 'collapse', target: '#filters', text:{original: 'Filters', swap: 'Close'}}, aria:{expanded: :false}, id: 'filter-btn'}
    Filters
  .row.filter-options.collapse{id: 'filters', aria:{hidden: :true, expanded: :false}}
    .row
      %form{:action => request.path, :method => 'get', :class =>'simple-form', id:'filter-options'}
        = hidden_field_tag :search, nil, value: params[:search]
        = hidden_field_tag :sort, nil, value: params[:sort]
        .row
          .search-input
            %label Institute
            = select_tag :institute,
                options_from_collection_for_select(Institution.all,  "id", "name", params[:institute]),
                                  include_blank: true
        .row
          .search-input
            %label Role
            = select_tag :role,
                options_from_collection_for_select(Role.all,  "id", "name", params[:role]),
                                  include_blank: true
        .row.search
          %button{:type =>"submit", :class => 'btn btn-secondary'}
            .fa.fa-search
            Apply Filters
          = link_to 'Clear', '/members', title: "Clear filters", :class => 'btn btn-secondary'

-# For each member, show name, institute, last seen time, and truncated bio
-# show based on member privacy settings
- @members.each do |m|
  .row.box.index-list
    .row
      .left-align.col-md-3
        %h3.name= m.name
        %h4.institute= m.institution.name
        -# used to calculate the last seen time
        - last_seen = Time.now - m.user.last_sign_in_at
        - time_scale = 'seconds'
        - if last_seen > 60
          - last_seen = (last_seen / 60)
          - time_scale = "minutes"
          - if last_seen > 60
            - last_seen = (last_seen / 60)
            - time_scale = "hours"
            - if last_seen > 24
              - last_seen = (last_seen / 24)
              - time_scale = "Days"
              - if last_seen > 7
                - last_seen = (last_seen / 7)
                - time_scale = 'Weeks'
                - if last_seen > 30
                  - last_seen = (last_seen / 30)
                  - time_scale = 'Months'
        %h6 Active #{last_seen.floor} #{time_scale} ago

      .left-align.content.bio.col-md-7
        -if m.bio_privacy_id == 1 || (user_signed_in? && m.bio_privacy_id ==2 && current_user.member.role_id != 4)
          =sanitize truncate(m.bio, length: 300, escape: false)
      .col-md-2.right-align
        = link_to 'View Profile', m,:class => 'btn btn-secondary', data:{turbolinks: false}

app/views/members/show.html.haml
-# This view is used to render the member_profile partial

- content_for :title, "#{@member[:name]}"
- content_for :header, "#{@member[:name]}"
= render 'layouts/standard_header'


.box.member
  = render 'member_profile'

app/views/members/update_failure.js.haml
-# This view will re-render the edit modal, show an error message
-# and scroll to the top

$('#modalWindow').html('#{j render template: 'members/edit'}');
$.flashAlert('An Error Occurred. Please Try Again', 'alert-alert');
$(this).scrollTop(0);

app/views/members/update_success.js.haml
-# This view will hide the current modal, re-render the profile
-# show a success message, and scroll to the top

$('#modalWindow').modal('hide');
$(".member").html($('#{j render 'member_profile'}'));
$.flashAlert('Profile Successfully Updated', 'alert-notice');
$(this).scrollTop(0);

app/views/members/validate_member.html.haml
-# this partial is used to change a member's authorisation level

.modal-dialog
  .modal-content.left-align
    = simple_form_for :auth, remote: true do |a|
      .modal-header
        %button.close{type: :button, data: {dismiss: :modal}}
          %span &times
        %h4.modal-title Edit #{@member.name}'s Authorisation Level
      .modal-body
        = a.select :role, options_from_collection_for_select(Role.where('id >= :current', current: current_user.member.role_id), "id", "name", @member.role_id)
      .modal-footer
        = a.button :submit, value: 'Update Authorisation Level', data:{disable_with: 'Please Wait...'}